version: '3'

services:
  backend:
    container_name: backend
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - 8000:8000
      - 9229:9229 # debugger port
    volumes:
      - ./backend/:/usr/src/app
      - /usr/src/app/node_modules
    command: npm run start:docker
    depends_on:
      - postgres
    environment:
      NODE_ENV: development
      PORT: 8000
      DATABASE_URL: ${DATABASE_URL}
      AWS_S3_BUCKET_URL: ${AWS_S3_BUCKET_URL}
      AWS_S3_LOCATION: ${AWS_S3_LOCATION}
      AWS_S3_KEY: ${AWS_S3_KEY}
      AWS_S3_SECRET: ${AWS_S3_SECRET}
      JWT_SECRET: ${JWT_SECRET}

  postgres:
    container_name: postgres
    image: postgres:14-alpine
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - db:/var/lib/postgresql/data

  frontend:
    container_name: frontend
    build:
      context: ./frontend
      target: builder
    ports:
      - 4200:4200
    depends_on:
      - backend
    environment:
      BACKEND_URL: https://localhost:8000
    volumes:
      - ./frontend:/usr/src/app
      - /usr/src/app/node_modules

volumes:
  db:
    driver: local
