version: '3'

services:
  backend:
    container_name: backend
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - 8000:8000
      - 9229:9229 # debugger port
    volumes:
      - ./backend/:/usr/src/app
      - /usr/src/app/node_modules
    command: npm run start:docker
    depends_on:
      - postgres
    environment:
      DATABASE_URL: postgres://postgres@postgres/handouceur_dev
      PORT: 8000

  postgres:
    container_name: postgres
    image: postgres:14-alpine
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: handouceur_dev
      POSTGRES_HOST_AUTH_METHOD: trust
    # FIXME: persist data
    # volumes:
    #   - ./postgres-data:/var/lib/postgresql/data

  frontend:
    container_name: frontend
    build:
      context: ./frontend
      target: builder
    ports:
      - 4200:4200
    depends_on:
      - backend
    environment:
      BACKEND_URL: https://localhost:8000
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./frontend:/project
      - /project/node_modules
