version: '3.1'

services:
  db:
    image: mysql
    restart: always
    # command: ""
    environment:
      MYSQL_DATABASE: 'prisma_db'
      # So you don't have to use root, but you can if you like
      MYSQL_USER: 'prisma'
      # You can use whatever password you like
      MYSQL_PASSWORD: 'password'
      # Password for root access
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      # <Port exposed> : < MySQL Port running inside container>
      - '3306:3306'
    expose:
      # Opens port 3306 on the container
      - '3306'
      # Where our data will be persisted
    volumes:
      - './prisma/migrations/20221113215541_init/migration.sql:/docker-entrypoint-initdb.d/1.sql'
# Names our volume
volumes:
  my-db: